"""add_s3_bucket_to_images

Revision ID: 05474fc47c67
Revises: 1905d12d2ed8
Create Date: 2026-04-12 04:49:17.597963
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05474fc47c67'
down_revision: Union[str, None] = '1905d12d2ed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('s3_bucket', sa.String(length=255), nullable=False, server_default='mlabled'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 's3_bucket')
    # ### end Alembic commands ###
