"""model_server_new_fields

Revision ID: 800ed8917417
Revises: 05474fc47c67
Create Date: 2026-04-12 08:07:32.860972
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '800ed8917417'
down_revision: Union[str, None] = '05474fc47c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_servers', sa.Column('supported_tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('model_servers', sa.Column('class_type', sa.String(length=50), nullable=False, server_default='fixed'))
    op.add_column('model_servers', sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.drop_column('model_servers', 'model_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_servers', sa.Column('model_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('model_servers', 'labels')
    op.drop_column('model_servers', 'class_type')
    op.drop_column('model_servers', 'supported_tasks')
    # ### end Alembic commands ###
